version: '3.8'

services:
  mysql:
    container_name: mysql
    build: backend/db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: learning_sys_db
      MYSQL_USER: student
      MYSQL_PASSWORD: student_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 15s
      retries: 10
      

  backend:
    build: backend/server
    container_name: backend
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend/server:/app
      - /app/__pycache__
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
  
  frontend:
    build: frontend
    working_dir: /app
    depends_on:
      - backend
    ports:
      - "4200:4200"
    command: "ng serve --host 0.0.0.0 --poll=2000 --port 4200 --disable-host-check"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

volumes:
  mysql_data:
